### ISSUE TITLE
[BUG] NZBGet pass error

### ISSUE THREAD

**Issue by StealUrKill** [linuxserver/docker-lazylibrarian#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installing docker using supplied compose and sets everything up fine but when testing connection to nzbget nothing shows up. Opening f12 (dev tools) shows and error 500 when hitting the test. Manually navigating to the test page shows

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
NZBGet works fine across radarr, sonarr, lidarr, readarr and others.

```
Traceback (most recent call last):
  File "/app/lazylibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/lazylibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/lazylibrarian/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/lazylibrarian/lazylibrarian/webServe.py", line 7661, in test_nzbget
    if self.validate_param("nzbget pass", kwargs['pass'], ['<', '>', '='], None):
KeyError: 'pass'
```

### Expected Behavior

Insert nzbget info and test connection successfull.

### Steps To Reproduce

Install via docker compose
Change settings/downloaders and hit test nzbget
Connection shows successfull.

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
lazylibrarian:
    image: linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    hostname: LazyLibrarian
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - /share/Container/data/lazylibrarian:/config
      - /share/Container/data/lazylibrarian:/downloads
      - /share/Public/Data:/books #optional
    ports:
      - 5299:5299
    restart: unless-stopped
    
  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    hostname: Readarr
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /share/Container/data/readarr:/config
      - /share/Public/Data:/data
    ports:
      - 8910:8787
    restart: unless-stopped
    
  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=America/Chicago
      - NZBGET_USER=admin #optional
      - NZBGET_PASS=nzbgetadmin #optional
    hostname: NZBGet
    volumes:
      - /share/Container/data/nzbget:/config
      - /share/Public/Data/usenet:/downloads
    ports:
      - 8989:6789
    restart: unless-stopped
```

### Container logs

```bash
____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________

        Traceback (most recent call last):
          File "calibre/linux.py", line 859, in setup_desktop_integration
          File "calibre/linux.py", line 881, in do_setup_desktop_integration
          File "calibre/linux.py", line 912, in install_xdg_junk
          File "calibre/linux.py", line 897, in install_icons
          File "calibre/linux.py", line 891, in install_single_icon
          File "subprocess.py", line 408, in check_call
          File "subprocess.py", line 389, in call
          File "subprocess.py", line 1026, in __init__
          File "subprocess.py", line 1950, in _execute_child
        FileNotFoundError: [Errno 2] No such file or directory: 'xdg-icon-resource'

Creating un-installer: /usr/bin/calibre-uninstall


There were 1 warnings

* Setting up desktop integration failed with error:

[custom-init] No custom files found, skipping...
2024-08-24 13:21:14,819 DEBUG: Set config[HOMEPAGE]=Authors [configtypes.py:160 (MAIN/special.configwrite)]
2024-08-24 13:21:14,819 DEBUG: Set config[CONFIG_TAB_NUM]=3 [configtypes.py:160 (MAIN/special.configwrite)]
2024-08-24 13:21:14,819 DEBUG: Set config[EBOOK_DIR]=/books [configtypes.py:160 (MAIN/special.configwrite)]
2024-08-24 13:21:14,819 DEBUG: Set config[DOWNLOAD_DIR]=/downloads [configtypes.py:160 (MAIN/special.configwrite)]
2024-08-24 13:21:14,819 DEBUG: Set config[API_ENABLED]=True [configtypes.py:160 (MAIN/special.configwrite)]
2024-08-24 13:21:14,819 DEBUG: Set config[API_KEY]=098ca32436e2101c83139cb1490fb8db [configtypes.py:160 (MAIN/special.configwrite)]
2024-08-24 13:21:14,819 DEBUG: Set config[LOGDIR]=/config/log [configtypes.py:160 (MAIN/special.configwrite)]
2024-08-24 13:21:14,819 DEBUG: Set config[LOGLEVEL]=50 [configtypes.py:160 (MAIN/special.configwrite)]
2024-08-24 13:21:14,822 DEBUG: Read config[LOGDIR]=/config/log [configtypes.py:144 (MAIN)]
2024-08-24 13:21:14,822 DEBUG: Read config[LOGSPECIALDEBUG]= [configtypes.py:144 (MAIN)]
/app/lazylibrarian/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'bootswatch.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
[ls.io-init] done.
```

**Comment by j0nnymoe** [comment]
This looks like an app issue, not a container issue. I would recommend seeking support from lazylibrarian github/devs.

**Comment by StealUrKill** [comment]
> This looks like an app issue, not a container issue. I would recommend seeking support from lazylibrarian github/devs.

I actually just fixed it. But it will actually be a problem for everyone since its in the source. 

If anyone else has this issue, you can fix it by ssh or run docker commands like so

`docker cp lazylibrarian:/app/lazylibrarian/lazylibrarian/webServe.py /path/to/your/data/webServe.py
`

Then change (for me) line 7661. Pasting the entire expose for nzbget

```
        if 'pwd' in kwargs:
            if self.validate_param("nzbget pass", kwargs['pass'], ['<', '>', '='], None):
                CONFIG.set_str('NZBGET_PASS', kwargs['pwd'])
```


To this

```
        if 'pwd' in kwargs:
            if self.validate_param("nzbget pass", kwargs['pwd'], ['<', '>', '='], None):
                CONFIG.set_str('NZBGET_PASS', kwargs['pwd'])
```

Then run

`docker cp /path/to/your/data/webServe.py lazylibrarian:/app/lazylibrarian/lazylibrarian/webServe.py`

Lastly

`docker restart lazylibrarian`


Pass on line 7661 needs to be pwd.

![Screenshot 2024-08-24 135604](https://github.com/user-attachments/assets/5d581fe5-6b58-478a-ad4a-7b3382439aa6)

**Comment by j0nnymoe** [comment]
This then should be reported upstream.

**Comment by StealUrKill** [comment]
> This then should be reported upstream.

for sure. I don't have a gitlab so I guess I will need to make one lol

Edit:
Completed

https://gitlab.com/LazyLibrarian/LazyLibrarian/-/issues/2643

**Comment by StealUrKill** [comment]
This should be good now

https://gitlab.com/LazyLibrarian/LazyLibrarian/-/commit/db937bebcad3178cae3717bb69ad3e30654a6443
